# Generated by Django 5.2.3 on 2025-06-28 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField()),
                ('kondisi', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], default='baik', max_length=20)),
                ('keterangan', models.TextField()),
                ('digunakan', models.IntegerField()),
                ('sisa', models.IntegerField()),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lokasi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FotoBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_barang', models.ImageField(blank=True, null=True, upload_to='foto_barang/')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='inventaris.barang')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='lokasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang', to='inventaris.lokasi'),
        ),
    ]
