# Generated by Django 5.2.3 on 2025-06-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='keterangan',
            new_name='deskripsi',
        ),
        migrations.AddField(
            model_name='lokasi',
            name='kode_lokasi',
            field=models.CharField(default='DEFAULT', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
