# Generated by Django 5.2.3 on 2025-06-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0002_rename_keterangan_barang_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name': 'Barang', 'verbose_name_plural': 'Barang'},
        ),
        migrations.AlterModelOptions(
            name='fotobarang',
            options={'verbose_name': 'Foto Barang', 'verbose_name_plural': 'Foto Barang'},
        ),
        migrations.AlterModelOptions(
            name='lokasi',
            options={'verbose_name': 'Lokasi', 'verbose_name_plural': 'Lokasi'},
        ),
        migrations.AlterField(
            model_name='barang',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='digunakan',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='barang',
            name='sisa',
            field=models.IntegerField(editable=False),
        ),
    ]
