# Generated by Django 5.2.3 on 2025-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0003_alter_barang_options_alter_fotobarang_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='digunakan',
            field=models.IntegerField(),
        ),
    ]
